/** Automatically generated by @palmares/drizzle-engine on 2025-02-24T03:01:03.513Z */ 

import * as d from '@palmares/drizzle-engine/pg-core';
import * as drzl from '@palmares/drizzle-engine/drizzle';

export const User = d.pgTable('user', {
  id: d.serial('id').primaryKey().unique(),
  firstName: d.varchar('first_name', { length: 255 }).notNull(),
  lastName: d.varchar('last_name', { length: 255 }).notNull(),
  email: d.text('email').notNull().unique(),
  isActive: d.boolean('is_active').notNull()
}, (table) => ({
  idIdx: d.uniqueIndex('user_id_idx').on(table.id)
}));

export const Analytics = d.pgTable('analytics', {
  id: d.serial('id').primaryKey().unique(),
  ip: d.text('ip').notNull(),
  userAgent: d.text('user_agent').notNull(),
  referer: d.text('referer').notNull(),
  shortId: d.integer('short_id').notNull().references((): d.AnyPgColumn => Shorter.id)
}, (table) => ({
  idIdx: d.uniqueIndex('analytics_id_idx').on(table.id)
}));

export const Shorter = d.pgTable('shorter', {
  id: d.serial('id').primaryKey().unique(),
  short: d.varchar('short', { length: 255 }).notNull(),
  long: d.text('long').notNull(),
  isActive: d.boolean('is_active').notNull(),
  userId: d.integer('user_id').notNull().references((): d.AnyPgColumn => User.id)
}, (table) => ({
  idIdx: d.uniqueIndex('shorter_id_idx').on(table.id)
}));

export const AnalyticsRelations = drzl.relations(Analytics, (args) => ({
  analyticsShorterLink: args.one(Shorter, {
    fields: [Analytics.shortId],
    references: [Shorter.id]
  })
}));

export const ShorterRelations = drzl.relations(Shorter, (args) => ({
  analyticsRecords: args.many(Analytics),
  userLink: args.one(User, {
    fields: [Shorter.userId],
    references: [User.id]
  })
}));

export const UserRelations = drzl.relations(User, (args) => ({
  shorterLinks: args.many(Shorter)
}));

